/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourceHealthRouteImport } from './routes/source-health'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as EconomyRouteImport } from './routes/economy'
import { Route as DisasterClimateRouteImport } from './routes/disaster-climate'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as IndexRouteImport } from './routes/index'

const SourceHealthRoute = SourceHealthRouteImport.update({
  id: '/source-health',
  path: '/source-health',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyRoute = EconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisasterClimateRoute = DisasterClimateRouteImport.update({
  id: '/disaster-climate',
  path: '/disaster-climate',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/disaster-climate': typeof DisasterClimateRoute
  '/economy': typeof EconomyRoute
  '/people': typeof PeopleRoute
  '/procurement': typeof ProcurementRoute
  '/regions': typeof RegionsRoute
  '/source-health': typeof SourceHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/disaster-climate': typeof DisasterClimateRoute
  '/economy': typeof EconomyRoute
  '/people': typeof PeopleRoute
  '/procurement': typeof ProcurementRoute
  '/regions': typeof RegionsRoute
  '/source-health': typeof SourceHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/disaster-climate': typeof DisasterClimateRoute
  '/economy': typeof EconomyRoute
  '/people': typeof PeopleRoute
  '/procurement': typeof ProcurementRoute
  '/regions': typeof RegionsRoute
  '/source-health': typeof SourceHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/disaster-climate'
    | '/economy'
    | '/people'
    | '/procurement'
    | '/regions'
    | '/source-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/disaster-climate'
    | '/economy'
    | '/people'
    | '/procurement'
    | '/regions'
    | '/source-health'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/disaster-climate'
    | '/economy'
    | '/people'
    | '/procurement'
    | '/regions'
    | '/source-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  DisasterClimateRoute: typeof DisasterClimateRoute
  EconomyRoute: typeof EconomyRoute
  PeopleRoute: typeof PeopleRoute
  ProcurementRoute: typeof ProcurementRoute
  RegionsRoute: typeof RegionsRoute
  SourceHealthRoute: typeof SourceHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/source-health': {
      id: '/source-health'
      path: '/source-health'
      fullPath: '/source-health'
      preLoaderRoute: typeof SourceHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disaster-climate': {
      id: '/disaster-climate'
      path: '/disaster-climate'
      fullPath: '/disaster-climate'
      preLoaderRoute: typeof DisasterClimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  DisasterClimateRoute: DisasterClimateRoute,
  EconomyRoute: EconomyRoute,
  PeopleRoute: PeopleRoute,
  ProcurementRoute: ProcurementRoute,
  RegionsRoute: RegionsRoute,
  SourceHealthRoute: SourceHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
